services:
  db:
    image: postgres:15-alpine
    container_name: testpos_db
    restart: always
    environment:
      POSTGRES_DB: testpos
      POSTGRES_USER: posuser
      POSTGRES_PASSWORD: pospass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
